const products = [
  { id: 1, nameZh: "电子灭鼠器", nameEn: "Electronic Rat Killer", price: 3.5, unit: "pcs", category: "3C", icon: "🐭", tag: "热销" },
  { id: 2, nameZh: "LED串灯", nameEn: "LED String Lights", price: 3.5, unit: "pcs", category: "3C", icon: "💡", tag: "新品" },
  { id: 3, nameZh: "LED小夜灯", nameEn: "LED Automatic Night Light", price: 1.5, unit: "pcs", category: "3C", icon: "🌙", tag: "" },
  { id: 4, nameZh: "无线门铃", nameEn: "Wireless Doorbell", price: 2.5, unit: "pcs", category: "3C", icon: "🔔", tag: "" },
  { id: 5, nameZh: "小音响", nameEn: "Mini Speaker", price: 4.0, unit: "pcs", category: "3C", icon: "🔊", tag: "" },
  { id: 6, nameZh: "小夜灯", nameEn: "Night Light", price: 3.0, unit: "pcs", category: "3C", icon: "🕯️", tag: "" },
  { id: 7, nameZh: "电源转换插座", nameEn: "Power Conversion Socket", price: 3.0, unit: "pcs", category: "3C", icon: "🔌", tag: "" },
  { id: 8, nameZh: "立体小夜灯", nameEn: "Three-Dimensional Night Light", price: 3.0, unit: "pcs", category: "3C", icon: "⭐", tag: "" },
  { id: 9, nameZh: "室内灭蚊灯", nameEn: "Indoor Mosquito Killer Lamp", price: 3.0, unit: "pcs", category: "3C", icon: "🦟", tag: "" },
  { id: 10, nameZh: "手持小电扇", nameEn: "Handheld Mini Fan", price: 1.5, unit: "pcs", category: "3C", icon: "🌀", tag: "" },
  { id: 11, nameZh: "颈部背部按摩器", nameEn: "Neck & Back Massager", price: 1.5, unit: "pcs", category: "3C", icon: "💆", tag: "" },
  { id: 12, nameZh: "吹风机", nameEn: "Hair Dryer", price: 4.0, unit: "pcs", category: "3C", icon: "💨", tag: "" },
  { id: 13, nameZh: "电脑键盘", nameEn: "Computer Keyboard", price: 4.0, unit: "pcs", category: "3C", icon: "⌨️", tag: "" },
  { id: 14, nameZh: "咖啡机", nameEn: "Coffee Machine", price: 7.5, unit: "pcs", category: "3C", icon: "☕", tag: "精品" },
  { id: 15, nameZh: "卡拉OK机", nameEn: "Karaoke Machine", price: 3.0, unit: "pcs", category: "3C", icon: "🎤", tag: "" },
  { id: 16, nameZh: "便携式触摸台灯", nameEn: "Portable Touch Lamp", price: 3.0, unit: "pcs", category: "3C", icon: "🪔", tag: "" },
  { id: 17, nameZh: "LED汽车大灯", nameEn: "LED Car Headlight", price: 3.0, unit: "pcs", category: "3C", icon: "🚗", tag: "" },
  { id: 18, nameZh: "电话机", nameEn: "Telephone", price: 4.0, unit: "pcs", category: "3C", icon: "📞", tag: "" },
  { id: 19, nameZh: "足底按摩器", nameEn: "Foot Massager", price: 4.5, unit: "pcs", category: "3C", icon: "🦶", tag: "" },
  { id: 20, nameZh: "电动牙刷", nameEn: "Electric Toothbrush", price: 2.0, unit: "pcs", category: "3C", icon: "🪥", tag: "" },
  { id: 21, nameZh: "抛绳玩具", nameEn: "Throwing Rope Toy", price: 2.8, unit: "pcs", category: "3C", icon: "🪀", tag: "" },
  { id: 22, nameZh: "椭圆电动脚底磨皮器", nameEn: "Electric Foot Callus Remover (Oval)", price: 2.0, unit: "pcs", category: "3C", icon: "🔮", tag: "" },
  { id: 23, nameZh: "圆柱电动脚底磨皮器", nameEn: "Electric Foot Callus Remover (Cylinder)", price: 2.6, unit: "pcs", category: "3C", icon: "🫧", tag: "" },
  { id: 24, nameZh: "电动直发梳", nameEn: "Hair Straightener Brush", price: null, unit: "pcs", category: "3C", icon: "💇", tag: "询价" },
  { id: 25, nameZh: "电动梳子", nameEn: "Electric Comb", price: null, unit: "pcs", category: "3C", icon: "🪮", tag: "询价" },
  { id: 26, nameZh: "筋膜枪", nameEn: "Massage Gun", price: null, unit: "pcs", category: "3C", icon: "🔫", tag: "询价" },
  { id: 27, nameZh: "儿童电动梳", nameEn: "Children's Electric Comb", price: 1.0, unit: "pcs", category: "3C", icon: "👧", tag: "新品" },
];
