const products = [
  { id: 1, nameZh: "电子灭鼠器", nameEn: "电子灭鼠器", price: 3.5, unit: "件", category: "3C", icon: "🐭", tag: "热销" },
  { id: 2, nameZh: "LED串灯", nameEn: "LED灯串", price: 3.5, unit: "件", category: "3C", icon: "🎄", tag: "新品" },
  { id: 3, nameZh: "LED小夜灯", nameEn: "LED自动夜灯", price: 1.5, unit: "件", category: "3C", icon: "🌙", tag: "" },
  { id: 4, nameZh: "无线门铃", nameEn: "无线门铃", price: 2.5, unit: "件", category: "3C", icon: "🔔", tag: "" },
  { id: 5, nameZh: "小音响", nameEn: "迷你音箱", price: 4.0, unit: "件", category: "3C", icon: "🔊", tag: "" },
  { id: 6, nameZh: "小夜灯", nameEn: "夜灯", price: 3.0, unit: "件", category: "3C", icon: "💡", tag: "" },
  { id: 7, nameZh: "电源转换适配器", nameEn: "电源转换插座", price: 3.0, unit: "件", category: "3C", icon: "🔌", tag: "" },
  { id: 8, nameZh: "立体小夜灯", nameEn: "立体夜灯", price: 3.0, unit: "件", category: "3C", icon: "⭐", tag: "" },
  { id: 9, nameZh: "室内灭蚊灯", nameEn: "室内灭蚊灯", price: 3.0, unit: "件", category: "3C", icon: "🦟", tag: "" },
  { id: 10, nameZh: "手持小电扇", nameEn: "手持迷你风扇", price: 1.5, unit: "件", category: "3C", icon: "🌀", tag: "" },
  { id: 11, nameZh: "重要的冠状装置", nameEn: "颈背按摩器", price: 1.5, unit: "件", category: "3C", icon: "💆", tag: "" },
  { id: 12, nameZh: "开头机", nameEn: "电吹风", price: 4.0, unit: "件", category: "3C", icon: "💨", tag: "" },
  { id: 13, nameZh: "电脑键盘", nameEn: "电脑键盘", price: 4.0, unit: "件", category: "3C", icon: "⌨️", tag: "" },
  { id: 14, nameZh: "咖啡机", nameEn: "咖啡机", price: 7.5, unit: "件", category: "3C", icon: "☕", tag: "精品" },
  { id: 15, nameZh: "卡拉OK机", nameEn: "卡拉OK机", price: 3.0, unit: "件", category: "3C", icon: "🎤", tag: "" },
  { id: 16, nameZh: "便携式触摸台灯", nameEn: "便携式触摸灯", price: 3.0, unit: "件", category: "3C", icon: "🪔", tag: "" },
  { id: 17, nameZh: "LED汽车大灯", nameEn: "LED汽车前大灯", price: 3.0, unit: "件", category: "3C", icon: "🚗", tag: "" },
  { id: 18, nameZh: "电话机", nameEn: "电话", price: 4.0, unit: "件", category: "3C", icon: "📞", tag: "" },
  { id: 19, nameZh: "足底器", nameEn: "足部按摩器", price: 4.5, unit: "件", category: "3C", icon: "🦶", tag: "" },
  { id: 20, nameZh: "电动沙发", nameEn: "电动牙刷", price: 2.0, unit: "件", category: "3C", icon: "🪥", tag: "" },
  { id: 21, nameZh: "撒绳玩具", nameEn: "投掷绳索玩具", price: 2.8, unit: "件", category: "3C", icon: "🪀", tag: "" },
  { id: 22, nameZh: "简易电动脚底磨皮器", nameEn: "电动足部老茧去除器(椭圆形)", price: 2.0, unit: "件", category: "3C", icon: "🦵", tag: "" },
  { id: 23, nameZh: "圆柱电动脚底磨皮器", nameEn: "电动足部老茧去除器(圆筒式)", price: 2.6, unit: "件", category: "3C", icon: "🦵", tag: "" },
  { id: 24, nameZh: "电动直发梳", nameEn: "直发梳", price: null, unit: "件", category: "3C", icon: "💇", tag: "询价" },
  { id: 25, nameZh: "电动梳子", nameEn: "电动梳子", price: null, unit: "件", category: "3C", icon: "🪮", tag: "询价" },
  { id: 26, nameZh: "筋膜枪", nameEn: "按摩枪", price: null, unit: "件", category: "3C", icon: "💪", tag: "询价" },
  { id: 27, nameZh: "儿童电动橇", nameEn: "儿童电动梳子", price: 1.0, unit: "件", category: "3C", icon: "👧", tag: "新品" },

  { id: 28, nameZh: "充电台灯-黑色细长款", nameEn: "Rechargeable Slim Cordless Table Lamp (Black)", price: 22.99, unit: "件", category: "家居", icon: "🖤", tag: "新品" },
  { id: 29, nameZh: "充电台灯-银色细长款", nameEn: "Rechargeable Slim Cordless Table Lamp (Silver)", price: 22.99, unit: "件", category: "家居", icon: "🪨", tag: "新品" },
  { id: 30, nameZh: "充电台灯-金色细长款", nameEn: "Rechargeable Slim Cordless Table Lamp (Gold)", price: 22.99, unit: "件", category: "家居", icon: "✨", tag: "热销" },
  { id: 31, nameZh: "充电台灯-墨绿色细长款", nameEn: "Rechargeable Slim Cordless Table Lamp (Green)", price: 22.99, unit: "件", category: "家居", icon: "🌿", tag: "新品" },
  { id: 32, nameZh: "创意平衡台灯-红白黑", nameEn: "Modern Balance Arc Table Lamp (Red/White/Black)", price: 26.99, unit: "件", category: "家居", icon: "🎨", tag: "精品" },
  { id: 33, nameZh: "日落投影氛围灯", nameEn: "Sunset Projection Atmosphere LED Lamp", price: 18.99, unit: "件", category: "家居", icon: "🌅", tag: "热销" },
  { id: 34, nameZh: "折叠露营提灯", nameEn: "Portable Foldable Rechargeable Camping Lantern", price: 12.99, unit: "件", category: "家居", icon: "🏕️", tag: "新品" },
  { id: 35, nameZh: "磁吸夹式多功能台灯", nameEn: "Magnetic Clip-On 3-in-1 LED Desk Lamp", price: 17.49, unit: "件", category: "家居", icon: "🔆", tag: "新品" },
  { id: 36, nameZh: "鹅颈软管台灯-白色", nameEn: "Flexible Gooseneck LED Desk Lamp (White)", price: 13.99, unit: "件", category: "家居", icon: "💡", tag: "新品" },
  { id: 37, nameZh: "水晶泡浴室镜前灯-3头", nameEn: "Crystal Bubble Vanity Wall Light 3-Light Chrome", price: 42.99, unit: "件", category: "家居", icon: "✨", tag: "精品" },
  { id: 38, nameZh: "水晶泡浴室镜前灯-5头", nameEn: "Crystal Bubble Vanity Wall Light 5-Light Chrome", price: 56.99, unit: "件", category: "家居", icon: "💎", tag: "精品" },
  { id: 39, nameZh: "水晶圆柱三头吊灯", nameEn: "Crystal Cylinder Pendant Light 3-Head Cluster", price: 52.99, unit: "件", category: "家居", icon: "🔮", tag: "精品" },
  { id: 40, nameZh: "菱形镂空吊灯-白色", nameEn: "Geometric Diamond Pendant Light Matte White", price: 32.99, unit: "件", category: "家居", icon: "🔷", tag: "新品" },
  { id: 41, nameZh: "几何环形吊灯", nameEn: "LED Ring Pendant Light Geometric Loop", price: 38.99, unit: "件", category: "家居", icon: "⭕", tag: "热销" },
  { id: 42, nameZh: "水晶条形吊灯-金色/绿色", nameEn: "Crystal Bar Linear Pendant Chandelier Gold/Green", price: 70.99, unit: "件", category: "家居", icon: "👑", tag: "精品" },
  { id: 43, nameZh: "硅胶木柄厨具5件套", nameEn: "Silicone Kitchen Utensil Set Wood Handle 5-Piece", price: 16.99, unit: "套", category: "厨房", icon: "🍳", tag: "热销" },
  { id: 44, nameZh: "硅胶厨房夹套装9寸&12寸", nameEn: "Silicone Kitchen Tongs Set 9-inch & 12-inch", price: 10.99, unit: "套", category: "厨房", icon: "🥢", tag: "新品" },
  { id: 45, nameZh: "不锈钢量杯量勺16件套", nameEn: "Stainless Steel Measuring Cups & Spoons 16-Piece", price: 12.99, unit: "套", category: "厨房", icon: "⚖️", tag: "热销" },
];
